---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: "sergio-idarraga-t-app"
  description: This is a Java Spring boot app with prometheus and loki integration
  annotations:
    backstage.io/techdocs-ref: dir:.
    backstage.io/kubernetes-label-selector: 'entity-id=sergio-idarraga-t-app'
    backstage.io/kubernetes-namespace: sergio-idarraga-t-app-monitoring
    argocd/app-name: "sergio-idarraga-t-app"
  links:
    - url: https://sergio-idarraga-t-app.obs-stack.eci-idp.click/api/
      title: Url Shortener App 
      icon: externalLink
spec:
  owner: students
  lifecycle: experimental
  type: service
  system: "system:default/obs-stack"
