site_name: sergio-idarraga-t-app
site_description: Java Spring boot app with prometheus and loki integration

nav:
  - Home: index.md
  - Bitácora del Experimento: Bitacora.md

plugins:
  - techdocs-core
